export const fighters = [
   {
      name: 'Annoyed Karen',
      health: '67',
      attack: '14 - 18',
      special: 'Passive Aggresiveness',
      weakness: 'Logical thinking',
      imageUrl:
         'https://meczajkowski.github.io/ultimate-pixel-championship/assets/annoyed-karen.png',
   },
   {
      name: 'Mad Suzie',
      health: '78',
      attack: '12 - 18',
      special: 'Fist Punch',
      weakness: 'Pink color',
      imageUrl: 'https://meczajkowski.github.io/ultimate-pixel-championship/assets/mad-suzie.png',
   },
   {
      name: 'Jenny Wick',
      health: '55',
      attack: '22 - 24',
      special: 'Pencil Stab',
      weakness: 'Contrast',
      imageUrl: 'https://meczajkowski.github.io/ultimate-pixel-championship/assets/jenny-wick.png',
   },
   {
      name: 'Purple Pie',
      health: '80',
      attack: '9 - 12',
      special: 'Roasting',
      weakness: 'Sunscreen',
      imageUrl: 'https://meczajkowski.github.io/ultimate-pixel-championship/assets/purple-pie.png',
   },
   {
      name: 'Pale Lora',
      health: '60',
      attack: '15 - 16',
      special: 'Bleach Splash',
      weakness: 'Candy Cotton',
      imageUrl: 'https://meczajkowski.github.io/ultimate-pixel-championship/assets/pale-lora.png',
   },
   {
      name: 'Ivy Irene',
      health: '70',
      attack: '10 - 14',
      special: 'Potion Pill',
      weakness: 'Broccoli',
      imageUrl: 'https://meczajkowski.github.io/ultimate-pixel-championship/assets/ivy-irene.png',
   },
];
